apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgCHsrShfS8eNopMGYsDA/Zy7XGhkkbajrb4eyXVH4KcD5WWGJSRXrimPrQwGpnf3i42/zfSW+VKyBnc6uGtHPL1WAt2YjITdZpUb2jnPun9ok49fGm/zKbEm8p0xXqgJ4p/bzlDgv8CKa9aSVYwq0+JqOhTeNssahEpjdpCfNGiDeVEmU9DPFgPv+uR3Rn5ixFQ+MdvcmiD8wWvcHdEs2qmZ/at/TGhsA9suWs/k4MxiEzZU/xm+6QU+8/fwzazmrM4PyLn3IpxacynMkAXu0S9Q2WVEcU/p8oOyD1qXfAdfTTjCHGOLWv2WNVDaxnXV88gQUaoXqCtbtpcCjrrb2AwOy3hN4oL0nPPRrgcF1YU1uRulhUjQr4t8u2GM+XZnRhfHDE4FV2bli0fL2lcdpBRAec81DtY2Pg6IbuCiiitEriBVdsyW+wDxwHl1xz5g+CuotKYzR27cnlRuZOYaj2m9Qv1dkkXJ42XnmK1h47HTxQFbQ3v6NqmR4NaLVvegfm3XUYXQQVGcTDEPcOc0jdcbASnv20UZVOSkNd5dZ+cM0mKGb1vwjTIIsjCrvNJkoQBzdXCPMSBh+2QlBal/ekI3I8cSzRwPzjhLV98A5frq3CKXLKQJPqeGLhpuCQkADP3S6vU+gk0jvCgRtvPhFzMkRIXIIq3v8xHxNLt9BPMEfRgliex3CpZEh5p1+akyoJwzMSoJI5rd0ykHmLllCsfKLQ8hhfydDA5Qo4JeJaaaBPZYjtT3H674w1yStzE1ZlxkTxxdkzaOxCFNAuVnA0fDeazcNSTEmnt78DDmeo6olwOVC7oWioj7TspCXqIat2PhVekWW928zaKzD7eq9txit2frZo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

