apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    creds: AgBXuuFAT8mHTP6HkLvm/teTRtQoHNHrH2kvv6/EfHWrHRfmnPR9L+yaCnTZRnp9fSRbphM/BjOwiN1FZHKAWR3t7uJ6zOdGtgLNQijTGLCGU9OBwDVCGqUkqailcVhlZEQyyTcYRy4sdFKQqYqYAb1/7BhRlM/wWvkzDO0vgYgyy0C+nUcSYEmI2jh/bYpfbqjxW+L/JAG8psLtDiwzZPeqaQ61F/V02FF2y/Juiok0zxjrljf8Xc+LxH5ozl9O5eTy8bwAochqBEmxC+5AGzQDnOs0J7ikAiPr+QunGK4BHMjOQBvJfvAwOTgUTUfHqtm7PTI7YWOwuY1jqoaDM/agEmIU2mq+G5QUh5v4EbzuZr11xHFP5a1IeNLy+k5ld6qxCaekoc0XhfA5Y7EjhGB23SqJ2InfvYQlhX+hGLFx0VzZmGQedbi2KF0Z3BlKIWO2S5vKc+mMc5+68VhFdwnGSoQblJks6ZThITSZmi3UvgePQ1ObXjpvHcc2cwSRZ5kVwsZT87zNNY6XOrqT3EeqhXz4ODthpz8VRNhrYPpL0KUcUTM7sFkQF5brfJ+yqn2iExEKRBfT11RWWSUJJU0PY34K2mEcTkW+9s0YG8ago5kJMuvFAgmUT0rCTF7k/5jsoyYkbckG9VKY4dXoiNu3Fw7vrY8sW2VuXjUt3IIVchPNhcqTmT6cwcSjCz4PloEXuIGmb6DpO0y/88VH9/SSMJ8nXNhwWYfWiOoqD4L2MWkUg7JskIN7rea4R1A+8xKEqVhX5A/NUke2DJkWhyySmM78Ylf8rRcIwW19kVE5uyKLOLFV8M5ZPQAjjyna+cAh+J2Ej0AZwQmakApwXSaVjBdd+qU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: aws-creds
      namespace: crossplane-system

