apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps-reqs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-app-reqs
    repoURL: https://github.com/ripro-patrick/crossplane-kubevela-argocd-demo
    targetRevision: HEAD
  destination:
    server: 
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
