apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-a-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: team-a-apps
    repoURL: https://github.com/ripro-patrick/crossplane-kubevela-argocd-demo
    targetRevision: HEAD
  destination:
    server: https://FDFE0C2AB8F6BF83AB6F13EE272E2A7D.gr7.eu-central-1.eks.amazonaws.com
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
